rm: cannot remove ‘logs/NGC4993_r83_m4.mem’: No such file or directory
/n/home01/bcook/.conda/envs/py36/lib/python3.6/site-packages/pysynphot/locations.py:46: UserWarning: PYSYN_CDBS is undefined; functionality will be SEVERELY crippled.
  warnings.warn("PYSYN_CDBS is undefined; functionality will be SEVERELY "
/n/home01/bcook/.conda/envs/py36/lib/python3.6/site-packages/pysynphot/locations.py:329: UserWarning: Extinction files not found in extinction
  warnings.warn('Extinction files not found in %s' % (extdir, ))
Traceback (most recent call last):
  File "/n/home01/bcook/pCMDs/pixcmd/pcmdpy/bin/pcmd_integrate", line 51, in <module>
    spec.loader.exec_module(config)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "setup_files/NGC4993/NGC4993_model4c.py", line 12, in <module>
    import pcmdpy_gpu as ppy
  File "/n/home01/bcook/pCMDs/pixcmd/pcmdpy/pcmdpy_gpu/__init__.py", line 3, in <module>
    gpu_utils.initialize_gpu()
  File "/n/home01/bcook/pCMDs/pixcmd/pcmdpy/pcmdpy/simulation/gpu_utils.py", line 64, in initialize_gpu
    import pycuda.autoinit
  File "/n/home01/bcook/.local/lib/python3.6/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.RuntimeError: cuInit failed: no CUDA-capable device is detected
